# Generated by Django 6.0.6 on 2026-06-19 02:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('type_annonce', models.CharField(choices=[('info', 'Information Générale'), ('vacances', 'Vacances / Congés'), ('ferie', 'Jour Férié')], default='info', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('date_evenement', models.DateField(blank=True, help_text="Date optionnelle du début de l'événement", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPrefet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('prefet', 'Préfet des Études'), ('dir_etudes', 'Directeur des Études'), ('dir_discipline', 'Directeur de Discipline'), ('secretaire', 'Secrétaire'), ('comptable', 'Comptable'), ('professeur', 'Professeur'), ('receptionniste', 'Réceptionniste'), ('eleve', 'Élève')], default='eleve', max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('photo_profil', models.ImageField(blank=True, default='profils/default.png', null=True, upload_to='profils/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoursAttribue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=100, verbose_name='Nom du Cours')),
                ('classe', models.CharField(max_length=50, verbose_name='Classe / Promotion')),
                ('heures_attribuees', models.IntegerField(verbose_name='Volume horaire total attribué')),
                ('heures_effectuees', models.IntegerField(default=0, verbose_name='Heures validées par le prof')),
                ('professeur', models.ForeignKey(limit_choices_to={'role': 'professeur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='SanctionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('retard', 'Retardateur Récurent'), ('puni', 'Élève Puni (Consigne/Retenue)'), ('exclu', 'Élève Exclu Temporairement')], max_length=20)),
                ('motif', models.TextField()),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide si permanent ou déjà réglé', null=True)),
                ('actif', models.BooleanField(default=True, help_text='Décochez si la punition est levée')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SituationEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_financier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bulletin_url', models.FileField(blank=True, null=True, upload_to='bulletins/')),
                ('eleve', models.OneToOneField(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
