# Generated by Django 6.0.6 on 2026-07-07 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_interro', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Note Interrogation / Travail Journalier')),
                ('note_examen', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Note Examen')),
                ('max_interro', models.IntegerField(default=20)),
                ('max_examen', models.IntegerField(default=40)),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('cours_attribue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_cours', to='core.coursattribue')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='mes_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Note de l'élève",
                'verbose_name_plural': 'Notes des élèves',
                'unique_together': {('eleve', 'cours_attribue')},
            },
        ),
    ]
