# Generated by Django 6.0.6 on 2026-07-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noteeleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='classe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='promotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
