# Generated by Django 6.0.6 on 2026-07-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fraisscolaire_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='bordereau',
            field=models.ImageField(blank=True, null=True, upload_to='bordereaux/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='note_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='recu_numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
